baseURL = "https://blog.euc-rt.me/"
languageCode = "en-us"
title = "Robert's Flummox Capacitor"
theme = "beautifulhugo"
DefaultContentLanguage = "en"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableEmoji = true
publishdir = "docs"


[Params]
  homeTitle = "Robert Terakedis" # Set a different text for the header on the home page
  subtitle = "Not to be confused with Pterodactyl..."
  mainSections = ["post","posts"]
  logo = "img/avatar-icon.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  gcse = "006263833525848905237:3xfwgq6zswl" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Robert Terakedis"
  website = "blog.euc-rt.me"
  # email = "youremail@domain.com"
  # facebook = "username"
  github = "rterakedis"
  # gitlab = "username"
  # bitbucket = "username"
  twitter = "robterakedis"
  # reddit = "username"
  linkedin = "terakedis"
  # xing = "username"
  # stackoverflow = "users/XXXXXXX/username"
  # snapchat = "username"
  # instagram = "username"
  # youtube = "user/username" # or channel/channelname
  # soundcloud = "username"
  # spotify = "username"
  # bandcamp = "username"
  # itchio = "username"
  # vk = "username"
  # paypal = "username"
  # telegram = "username"
  # 500px = "username"
  # codepen = "username"
  # mastodon = "url"
  # kaggle = "username"
  # weibo = "username"
  # slack = "username"


[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    identifier = "work"
    name = "My Work Content"
    weight = 2

[[menu.main]]
    parent = "work"
    name = "VMware EUC TechZone"
    url = "https://techzone.vmware.com/users/robert-terakedis"
    weight = 1

[[menu.main]]
    parent = "work"
    name = "VMware Tech Network"
    url = "https://communities.vmware.com/people/rterakedis/activity"
    weight = 2

[[menu.main]]
    parent = "work"
    name = "VMware EUC Samples"
    url = "https://github.com/vmware-samples/euc-samples/tree/master/macOS-Samples"
    weight = 3

[[menu.main]]
    parent = "work"
    name = "VMware EUC Blog"
    url = "https://blogs.vmware.com/euc/author/rterakedis"
    weight = 4

[[menu.main]]
    identifier = "resources"
    name = "Resources"
    weight = 3

[[menu.main]]
    parent = "resources"
    name = "Stickers"
    url = "/stickers/"
    weight = 1

[[menu.main]]
    parent = "resources"
    name = "Getting Started"
    url = "/gettingstarted/"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 4
